apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: nginx
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # 关闭强制跳https
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - testing.host.com
    secretName: nginx-ingress-secret
  rules:
  - host: testing.host.com
    http:
      paths:
      - path: /
        backend:
          # 与Service Port保持一致
          servicePort: 80
          # 与Service服务名称保持一致
          serviceName: nginx
